name: Docker Version Release

on:
  create:
    tags:
      - v*

jobs:

  docker-version:
    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kometa:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push lxml Version
        id: docker_build_lxml
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.lxml
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kometa:lxml-${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Discord Success Notification
        uses: meisnate12/discord-notifications@master
        if: success()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          title: "${{ steps.get_version.outputs.VERSION }} build: **Success**"
          url: https://github.com/kometa-Team/Kometa/actions/runs/${{ github.run_id }}
          username: Kometa Releases
          avatar_url: https://raw.githubusercontent.com/kometa-Team/Kometa/master/.github/kometa.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/kometa-Team/Kometa/master/.github/docker.png

      - name: Discord Failure Notification
        uses: meisnate12/discord-notifications@master
        if: failure()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          message: <@&1079153184007790652>
          title: "${{ steps.get_version.outputs.VERSION }} build: **Failure**"
          color: 0xe30c43
          url: https://github.com/kometa-Team/Kometa/actions/runs/${{ github.run_id }}
          username: Kometa Releases
          avatar_url: https://raw.githubusercontent.com/kometa-Team/Kometa/master/.github/kometa.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/kometa-Team/Kometa/master/.github/docker.png

      - name: Checkout Configs Repo
        uses: actions/checkout@v4
        with:
          repository: kometa-Team/Kometa-Configs
          token: ${{ secrets.PAT }}
          path: kometaconfigs

      - name: Create & Push Tag
        working-directory: ./kometaconfigs
        run: |
          git tag ${{ steps.get_version.outputs.VERSION }}
          git push origin ${{ steps.get_version.outputs.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG
          token: ${{ secrets.PAT }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}